// Code generated by MockGen. DO NOT EDIT.
// Source: internal/store/interface.go

// Package store is a generated GoMock package.
package store

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	serverservice "go.hollow.sh/serverservice/pkg/api/v1"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// BatchBomsUpload mocks base method.
func (m *MockRepository) BatchBomsUpload(ctx context.Context, boms []serverservice.Bom) (*serverservice.ServerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchBomsUpload", ctx, boms)
	ret0, _ := ret[0].(*serverservice.ServerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchBomsUpload indicates an expected call of BatchBomsUpload.
func (mr *MockRepositoryMockRecorder) BatchBomsUpload(ctx, boms interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchBomsUpload", reflect.TypeOf((*MockRepository)(nil).BatchBomsUpload), ctx, boms)
}

// GetAOCMacAddr mocks base method.
func (m *MockRepository) GetAOCMacAddr(ctx context.Context, macAddr string) (*serverservice.Bom, *serverservice.ServerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAOCMacAddr", ctx, macAddr)
	ret0, _ := ret[0].(*serverservice.Bom)
	ret1, _ := ret[1].(*serverservice.ServerResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAOCMacAddr indicates an expected call of GetAOCMacAddr.
func (mr *MockRepositoryMockRecorder) GetAOCMacAddr(ctx, macAddr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAOCMacAddr", reflect.TypeOf((*MockRepository)(nil).GetAOCMacAddr), ctx, macAddr)
}
